# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.4.3
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}

